### ISSUE TITLE
incorrect link on GitHub repo

### ISSUE THREAD

**Issue by IndrajeetPatil** [xoopR/R62S3#9]
This is 404:

<img width="304" alt="Screenshot 2021-07-16 at 08 55 58" src="https://user-images.githubusercontent.com/11330453/125905420-b2adb617-5dad-4bca-ab23-bbc045e8c8a9.png">

Found the current link in the `DESCRIPITON` file: https://xoopr.github.io/R62S3/

**Comment by RaphaelS1** [comment]
Thanks, updated
